# Generated by Django 4.1.7 on 2023-06-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_name', models.CharField(max_length=255)),
                ('nominee_number', models.CharField(max_length=20)),
                ('nominee_email', models.EmailField(max_length=254)),
                ('nominee_location', models.CharField(max_length=255)),
                ('event_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('social_media', models.CharField(max_length=255)),
                ('nominee_picture', models.ImageField(upload_to='nominee_pictures')),
                ('reason_for_filing', models.TextField()),
            ],
        ),
    ]
