# Generated by Django 4.1.2 on 2023-06-13 20:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0003_alter_nominee_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('unit_price', models.FloatField()),
                ('sponsors', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='nominee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting_app.event'),
        ),
    ]
