# Generated by Django 4.1.2 on 2023-06-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0004_event_alter_nominee_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nominee',
            name='event',
        ),
    ]
