# Generated by Django 4.1.2 on 2023-06-13 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0005_remove_nominee_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nominee',
        ),
    ]
