# Generated by Django 4.1.2 on 2023-06-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0007_nominee'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
