# Generated by Django 4.1.2 on 2023-06-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0009_alter_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='images.jpg', upload_to='event_images'),
        ),
    ]
