# Generated by Django 4.1.2 on 2023-06-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting_app', '0011_rename_nominee_picture_nominee_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee_location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='nominee',
            old_name='nominee_number',
            new_name='number',
        ),
    ]
